export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Fresh Tomatoes',
    price: 1000,
    image: '/images/tomatoes.jpeg',
  },
  {
    id: '2',
    name: 'Organic Carrots',
    price: 800,
    image: '/images/carrots.jpeg',
  },
  {
    id: '3',
    name: 'Garden Eggs',
    price: 1200,
    image: '/images/garden-eggs.jpeg',
  },
  {
    id: '4',
    name: 'Sweet Potatoes',
    price: 950,
    image: '/images/sweet-potatoes.jpeg',
  },
  {
    id: '5',
    name: 'Bell Peppers',
    price: 1500,
    image: '/images/bell-peppers.jpeg',
  },
  {
    id: '6',
    name: 'Red Onions',
    price: 700,
    image: '/images/red-onions.jpeg',
  },
  {
    id: '7',
    name: 'Spinach Bunch',
    price: 600,
    image: '/images/spinach.jpeg',
  },
  {
    id: '8',
    name: 'Cucumbers',
    price: 550,
    image: '/images/cucumbers.jpeg',
  },
  {
    id: '9',
    name: 'Cabbage',
    price: 1300,
    image: '/images/cabbage.jpeg',
  },
  {
    id: '10',
    name: 'Ewedu (Jute Leaves)',
    price: 1400,
    image: '/images/ewedu.jpeg',
  },
  {
    id: '11',
    name: 'Bitterleaf (Onugbu)',
    price: 850,
    image: '/images/bitterleaf.jpeg',
  },
  {
    id: '12',
    name: 'Okra',
    price: 900,
    image: '/images/okra.jpeg',
  },
  {
    id: '22',
    name: 'Palm Oil (5 Litres)',
    price: 6000,
    image: '/images/palmoil.jpeg',
  },
  {
    id: '23',
    name: 'Groundnut Oil (5 Litres)',
    price: 7500,
    image: '/images/groundnutoil.jpeg',
  },
  {
    id: '24',
    name: 'Yam Tubers',
    price: 3000,
    image: '/images/yam.jpeg',
  },
  {
    id: '28',
    name: 'Stockfish (Okporoko)',
    price: 8000,
    image: '/images/stockfish.jpeg',
  },
  {
    id: '30',
    name: 'Ogbono Seeds',
    price: 2500,
    image: '/images/ogbono.jpeg',
  },
  {
    id: '31',
    name: 'Egusi (Melon Seeds)',
    price: 2000,
    image: '/images/egusi.jpeg',
  },
  {
    id: '32',
    name: 'Garri (Cassava Flakes)',
    price: 1500,
    image: '/images/garri.jpeg',
  },
  {
    id: '34',
    name: 'Beans (Brown, Oloyin)',
    price: 1800,
    image: '/images/beans.jpeg',
  },
  {
    id: '35',
    name: 'Smoked Prawns/Shrimp',
    price: 4000,
    image: '/images/shrimp.jpeg',
  },
  {
    id: '36',
    name: 'Pepper (Ata rodo)',
    price: 900,
    image: '/images/pepper.jpeg',
  },
  {
    id: '39',
    name: 'Plantain (Unripe)',
    price: 900,
    image: '/images/plantain.jpeg',
  },
  {
    id: '40',
    name: 'Cocoa Yam',
    price: 1100,
    image: '/images/cocoayam.jpeg',
  },
  {
    id: '41',
    name: 'Rice (Ofada)',
    price: 2800,
    image: '/images/rice.jpeg',
  },
  {
    id: '11',
    name: 'Fluted pumpkin(ugwu)',
    price: 850,
    image: '/images/fluted-pumpkin.jpeg',
  },
  {
    id: '12',
    name: 'Green Beans',
    price: 900,
    image: '/images/green-beans.jpeg',
  },
  {
    id: '14',
    name: 'Garlic Bulbs',
    price: 400,
    image: '/images/garlic.webp',
  },
  {
    id: '15',
    name: 'Ginger Root',
    price: 750,
    image: '/images/ginger.jpeg',
  },
  {
    id: '16',
    name: 'Lemons',
    price: 300,
    image: '/images/lemons.jpeg',
  },
  {
    id: '17',
    name: 'Limes',
    price: 250,
    image: '/images/limes.jpeg',
  },
  {
    id: '18',
    name: 'Avocados (Hass)',
    price: 2000,
    image: '/images/herobanner3.jpeg',
  },
  {
    id: '19',
    name: 'Bananas (Bunch)',
    price: 500,
    image: '/images/bananas.jpeg',
  },
  {
    id: '20',
    name: 'Apples (Fuji)',
    price: 1100,
    image: '/images/apples.jpeg',
  },
  {
    id: '21',
    name: 'Oranges (Navel)',
    price: 900,
    image: '/images/oranges.jpeg',
  },
  {
    id: '22',
    name: 'Grapes (Red Seedless)',
    price: 2500,
    image: '/images/grapes.jpeg',
  },
  {
    id: '23',
    name: 'Strawberries (Punnet)',
    price: 1800,
    image: '/images/strawberries.jpeg',
  },
  {
    id: '25',
    name: 'Mangoes',
    price: 1700,
    image: '/images/mangoes.jpeg',
  },
  {
    id: '26',
    name: 'Pineapple',
    price: 2800,
    image: '/images/pineapple.jpeg',
  },
  {
    id: '27',
    name: 'Watermelon (Whole)',
    price: 3500,
    image: '/images/watermelon.jpeg',
  },
  {
    id: '29',
    name: 'Potatoes (Irish)',
    price: 1200,
    image: '/images/irish-potatoes.jpeg',
  },
];
